22 nccontainer
senacgo-hugotannus/nutri-calc-frontend pull request #38
Opened 2024-10-10 14:22 UTC by hugera

Criação do Componente "NCContainer"

2024-10-10 14:36 UTC, Enildo5 approved these changes

2024-10-11 14:21 UTC, Enildo5 submitted a review, later dismissed

2024-10-11 14:59 UTC, hugotannus requested changes
- Rever a utilização do componente `NCContainer` no arquivo `App.vue`;
- Avaliar/aplicar sugestões de limpeza de código.

2024-10-11 14:59 UTC, hugotannus commented on src/App.vue
> +    <NCContainer>
Não é recomendável utilizar o mesmo container tanto para a **barra de navegação** quanto para o **conteúdo principal** da página.

Ao invés disso, um exemplo de abordagem mais adequada seria utilizar dois containers: um para a barra de navegação...

```
<header>
  <NCContainer>
    <div class="wrapper">...</div>
  </NCContainer>
</header>
```

2024-10-11 14:59 UTC, hugotannus commented on src/App.vue
> +        <RouterView />
... e o outro componente `NCContainer` para _envolver_ o `RouterView`:

```
<main>
  <NCContainer>
    <RouterView />
  </NCContainer>
</main>
```

2024-10-11 14:59 UTC, hugotannus commented on src/views/CalculationView.vue
> +
Remover espaços desnecessários.

2024-10-11 14:59 UTC, hugotannus commented on src/views/CalculationView.vue
> +
**Dica:** Experimente utilizar (novamente) o comando `npm run lint`

2024-10-11 14:59 UTC, hugotannus commented on src/components/NCContainer.vue
> +
Remover quebras de linhas desnecessárias.

2024-10-11 14:59 UTC, hugotannus commented on src/components/NCContainer.vue
> +<style scoped>
Mesmo que haja previsão de alguma implementação de estilo para este componente, a tag de estilos pode ser removida enquanto não houver necessidade.

2024-10-14 11:56 UTC, hugera commented
Refatoração Concluída.

2024-10-14 12:04 UTC, hugotannus approved these changes

2024-10-14 12:08 UTC, zGuxta approved these changes

2024-10-14 12:10 UTC, carlos-henrique08 approved these changes

2024-10-14 12:10 UTC, merged